export const KORISNIK_PRIJAVA_ZAHTJEV = 'KORISNIK_PRIJAVA_ZAHTJEV';
export const KORISNIK_PRIJAVA_USPJEH = 'KORISNIK_PRIJAVA_USPJEH';
export const KORISNIK_PRIJAVA_NEUSPJEH = 'KORISNIK_PRIJAVA_NEUSPJEH';

export const KORISNIK_REGISTRACIJA_ZAHTJEV = 'KORISNIK_REGISTRACIJA_ZAHTJEV';
export const KORISNIK_REGISTRACIJA_USPJEH = 'KORISNIK_REGISTRACIJA_USPJEH';
export const KORISNIK_REGISTRACIJA_NEUSPJEH = 'KORISNIK_REGISTRACIJA_NEUSPJEH';

export const KORISNIK_ODJAVA = 'KORISNIK_ODJAVA';

export const KORISNIK_UREDI_ZAHTJEV = 'KORISNIK_UREDI_ZAHTJEV';
export const KORISNIK_UREDI_USPJEH = 'KORISNIK_UREDI_USPJEH';
export const KORISNIK_UREDI_NEUSPJEH = 'KORISNIK_UREDI_NEUSPJEH';
