export const KORPA_DODAJ_ARTIKAL = 'KORPA_DODAJ_ARTIKAL';
export const KORPA_UKLONI_ARTIKAL = 'KORPA_UKLONI_ATRIKAL';
export const KORPA_SACUVAJ_DOSTAVU = 'KORPA_SACUVAJ_DOSTAVU';
export const KORPA_SACUVAJ_PLACANJE = 'KORPA_SACUVAJ_PLACANJE';