/*PROIZVOD_LISTA_ZAHTJEV,  PROIZVOD_LISTA_USPJEH i PROIZVOD_LISTA_NEUSPJEH... su konstante*/
export const PROIZVOD_LISTA_ZAHTJEV = 'PROIZVOD_LISTA_ZAHTJEV';
export const PROIZVOD_LISTA_USPJEH = 'PROIZVOD_LISTA_USPJEH';
export const PROIZVOD_LISTA_NEUSPJEH = 'PROIZVOD_LISTA_NEUSPJEH';

export const PROIZVOD_DETALJI_ZAHTJEV = 'PROIZVOD_DETALJI_ZAHTJEV';
export const PROIZVOD_DETALJI_USPJEH = 'PROIZVOD_DETALJI_USPJEH';
export const PROIZVOD_DETALJI_NEUSPJEH = 'PROIZVOD_DETALJI_NEUSPJEH';

export const PROIZVOD_SACUVAJ_ZAHTJEV = 'PROIZVOD_SACUVAJ_ZAHTJEV';
export const PROIZVOD_SACUVAJ_USPJEH = 'PROIZVOD_SACUVAJ_USPJEH';
export const PROIZVOD_SACUVAJ_NEUSPJEH = 'PROIZVOD_SACUVAJ_NEUSPJEH';

export const PROIZVOD_IZBRISI_ZAHTJEV = 'PROIZVOD_IZBRISI_ZAHTJEV';
export const PROIZVOD_IZBRISI_USPJEH = 'PROIZVOD_IZBRISI_USPJEH';
export const PROIZVOD_IZBRISI_NEUSPJEH = 'PROIZVOD_IZBRISI_NEUSPJEH';
